# Generated by Django 5.0.1 on 2024-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpkey',
            name='secret_key',
            field=models.CharField(max_length=40),
        ),
    ]
