# Generated by Django 4.1.13 on 2024-03-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_otpkey_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpkey',
            name='user',
        ),
    ]
